apiVersion: monocron.io/v1
kind: Task
metadata:
  name: backup-db
spec:
  schedule: "5 * * * *"
  timezone: "Africa/Lagos"
  concurrencyPolicy: Forbid
  retry:
    maxAttempts: 2
    backoff: "15s,30s,2m,5m"
  executor:
    type: process
    command: ["pg_dump"]
    args: ["-h", "db.internal", "-U", "admin", "mydb"]
